name: Verify and Publish

on:
  push:
  workflow_dispatch:
    inputs:
      segment:
        description: "The version segment to increment: major, minor, patch, or prerelease."
        required: true
      preId:
        description: 'Appended to the prerelease segment. (default: "")'

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint-eslint
      - name: Prettier
        run: npm run lint-prettier
      - name: depcheck
        run: npm run lint-depcheck

      - name: Test Base
        run: npm run test:base
      - name: Test Base Strict
        run: npm run test:base-strict
      - name: Test React
        run: npm run test:react
      - name: Test React Strict
        run: npm run test:react-strict

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: verify

    if: github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Determine Tag
        id: publish-tag
        shell: bash
        run: |
          if [[ ${{ inputs.segment }} == pre* ]]; then
            echo "tag=next" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Increment Version
        shell: bash
        run: |
          git config --local user.name "Workflow: ${{ github.workflow }}"
          git config --local user.email "${{ github.workflow }}@workflow"

          if [[ ${{ inputs.segment }} == pre* ]]; then
            if [[ -n "${{ inputs.preId }}" ]]; then
              PREID_CMD="--preid ${{ inputs.preId }}"
            fi
          fi

          npm version ${{ inputs.segment }} -m "Publish v%s" $PREID_CMD

      - name: Publish to GitHub Packages Registry
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: "https://npm.pkg.github.com/"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.publish-tag.outputs.tag }}
          access: public

      - name: Publish to NPM Registry
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: "https://registry.npmjs.org/"
          token: ${{ secrets.REGISTRY_TOKEN_NPM }}
          tag: ${{ steps.publish-tag.outputs.tag }}
          access: public

      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
